- name: Creates brick directory
  file:
    state: directory
    path: "{{ item.brick_dir }}"
  with_items: "{{ gluster_volumes }}"

- name: Creates volumes
  gluster_volume:
    state: present
    name: "{{ item.name }}"
    bricks: "{{ item.brick_dir }}"
    replicas: "{{ groups[gluster_servers_group] | length }}"
    cluster: "{{ groups[gluster_servers_group] | join('-' + gluster_interface + ',') }}"
    host: "{{ inventory_hostname }}"
    force: yes
    options:
      performance.cache-size: "{{ gluster_performance_cache_size }}"
      nfs-disable: "{{ gluster_nfs_disable }}"
  run_once: true
  with_items: "{{ gluster_volumes }}"
