- name: Creates brick directory
  file:
    state: directory
    path: "{{ gluster_bricks_dir }}/{{ gluster_brick_name }}"

- name: Creates volumes
  gluster_volume:
    state: present
    name: "{{ item.name }}"
    brick: "{{ item.brickdir }}"
    replicas: "{{ groups[gluster_servers_group] | length }}"
    cluster: "{{ groups[gluster_servers_group] | join('-' + gluster_interface + ',') }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true
  with_items: gluster_volumes
